# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_darwin_amd64.tar.gz"
      sha256 "550fbff4a42d99d707ab612a407ef646068ad26567c98da5d6eafc72bef69d34"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_darwin_arm64.tar.gz"
      sha256 "9a10b9a9d6dab8add33d13756b32de5c8ea099b13a15a477a79b736c2df7592a"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_linux_amd64.tar.gz"
      sha256 "2c2b1398dea675a036bed94a79e660ee0f149983f80637ab4bdc1baa568501c1"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_linux_arm64.tar.gz"
      sha256 "a073113b0e3a1b334b388257741aeec4a713287ca13a621ce73c8e44a8b806a7"
      def install
        bin.install "lazylms"
      end
    end
  end
end
