# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_darwin_amd64.tar.gz"
      sha256 "d5f00bc6f61ff99c47e988b4373f69d562588ade98fe02a314a2f968ce2445c0"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_darwin_arm64.tar.gz"
      sha256 "60ca5ab3f56ed707d53b4013ded897474d79eb6e28d0e3d3d11ec53268e9e000"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_linux_amd64.tar.gz"
      sha256 "83690d6f1ba43fb0f6f61d0c7f444223bb82a0bd590820f066a79a6ab99d768a"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.1/lazylms_1.0.0-beta.1_linux_arm64.tar.gz"
      sha256 "bcd4daf515749e96880ce7caf19ee2f22da6c86fbdec9ae2136896f904aa46cd"
      def install
        bin.install "lazylms"
      end
    end
  end
end
