# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_darwin_amd64.tar.gz"
      sha256 "f74eb7900406b0f4930721bd59702951c81998c22504bbddf2a08c742f9b8c5e"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_darwin_arm64.tar.gz"
      sha256 "18242a83dd5c935fdd88f29365d1c5ecd3861f7849a5b288e423bbba722632e0"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_linux_amd64.tar.gz"
      sha256 "b6a6b8dd6855843d915ddd7da5c8fb3f1da499cc6b7b75d9c622bdac7aaf86b0"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_linux_arm64.tar.gz"
      sha256 "f236496263983fb40b462aaed9127667ae4499e4d893cce9631bae2de45c4180"
      def install
        bin.install "lazylms"
      end
    end
  end

  test do
    system "#{bin}/lazylms", "--help"
  end
end
