# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_darwin_amd64.tar.gz"
      sha256 "0091f63da66932cace427ce27b0b8d7af35df80ae5e213a9b9f58b18b04b2a21"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_darwin_arm64.tar.gz"
      sha256 "16d94bf452526386318bd14a00dcd28c33635f4b7fa6dac59f2128631f17b92f"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_linux_amd64.tar.gz"
      sha256 "256a6ec1abdb2ff46b3b9a996b99d37887f4252efd5119cf7284190075c33ebe"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.3/lazylms_1.0.0-beta.3_linux_arm64.tar.gz"
      sha256 "957e619ab28c72107f21a2286ba964d0d95eaadf25a2f4f9471374d40cc8bae9"
      def install
        bin.install "lazylms"
      end
    end
  end

  test do
    system "#{bin}/lazylms", "--help"
  end
end
