# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.7/lazylms_1.0.0-beta.7_darwin_amd64.tar.gz"
      sha256 "dc2f50523e98111e7c6bc277acfb7528d0fdbd93732139d2886f7921ad4fde29"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.7/lazylms_1.0.0-beta.7_darwin_arm64.tar.gz"
      sha256 "65a6744fc2a66d95dd31b763c9db3dd364b46624338773c619d597365754dbf4"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.7/lazylms_1.0.0-beta.7_linux_amd64.tar.gz"
      sha256 "4820bc8f2d8415bd7efc834948e7cb7021b113bf96bba3d834956fbd680de7f7"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.7/lazylms_1.0.0-beta.7_linux_arm64.tar.gz"
      sha256 "4e66fd57a53e39c9606fcf03135647fb2ef4baff7a7e85bd7c680e8fe808d48d"
      def install
        bin.install "lazylms"
      end
    end
  end

  test do
    system "#{bin}/lazylms", "--help"
  end
end
