# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazylms < Formula
  desc "A minimal TUI client for LM Studio"
  homepage "https://github.com/Rugz007/lazylms"
  version "1.0.0-beta.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.5/lazylms_1.0.0-beta.5_darwin_amd64.tar.gz"
      sha256 "34870e31411e2576180ca6d0eb320b702d94e3fded284bda2c69a09e284c0f7d"

      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.5/lazylms_1.0.0-beta.5_darwin_arm64.tar.gz"
      sha256 "7f5ed581823d9e3294fa6fe60042bf885d734458132452ff76963bb8eb21854f"

      def install
        bin.install "lazylms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.5/lazylms_1.0.0-beta.5_linux_amd64.tar.gz"
      sha256 "7a86cf7f9b9aeb9f55bf7bc07905abf54058f3336027e0f631f1ea64bb5a5485"
      def install
        bin.install "lazylms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rugz007/lazylms/releases/download/v1.0.0-beta.5/lazylms_1.0.0-beta.5_linux_arm64.tar.gz"
      sha256 "ba937a885817709673fde1b3834a514521f118a336fce5c5b1846ecaf77a2aa6"
      def install
        bin.install "lazylms"
      end
    end
  end

  test do
    system "#{bin}/lazylms", "--help"
  end
end
